version: '3'
services:
        web:
                image: fruit_port_v1
                build: .
                ports:
                        - "8026:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped